### ISSUE TITLE
Hide decorative icons from keyboard and screen reader users

### ISSUE THREAD

**Issue by matuzo** [MadeByMike/supermaya#10]
Logo and login icon in main nav:
SVGs are focusable in IE 11, you want to add focusable="false" to the `<svg>`. While you're at it, you can also add `aria-hidden="true"` to really make sure that the svgs are hidden from screen readers.

```
<svg focusable="false" aria-hidden="true">…</svg>
```

**Comment by MadeByMike** [comment]
Brilliant thanks! Was this all you found?

**Comment by matuzo** [comment]
You're welcome! :)

No, I've created more issues and I'm not done checking but don't expect anything critical. Of course, you did a fantastic job.

**Comment by MadeByMike** [comment]
Thanks mate! I owe you one!

**Comment by matuzo** [comment]
I'm glad that I could contribute something!
