### ISSUE TITLE
Remove/Fix empty link

### ISSUE THREAD

**Issue by matuzo** [MadeByMike/supermaya#11]
The last link (login) in the footer navigation has no text content. It's focusable with the keyboard (at least in Firefox) and might be focusable by some screen readers as well.

<img width="477" alt="Bildschirmfoto 2019-11-05 um 10 29 51" src="https://user-images.githubusercontent.com/1496761/68269084-bd396a00-0058-11ea-991f-7129b8d778b4.png">

**Comment by MadeByMike** [comment]
Yep that's a recent bug that should be fixed.
