### ISSUE TITLE
Name landmarks 

### ISSUE THREAD

**Issue by matuzo** [MadeByMike/supermaya#13]
You have multiple nav landmarks, you should name them.
See https://www.scottohara.me/blog/2018/03/03/landmarks.html#multiple-landmark-roles-of-the-same-type

Also, you may not the a `<nav>` element in the footer since the links in the footer navigation are the same as in the main navigation.

**Comment by MadeByMike** [comment]
Thanks I'll make sure I add aria label aria labels. 

I want to keep it in the footer as a UX/Design thing. On longer pages it might make sense when you get to the bottom of the page to navigate somewhere else on the site. 

If nothing else looks good on for templated example with little content that people can change.

Is there some way I can let screen-readers know they are repeated links?

**Comment by matuzo** [comment]
Sorry, I didn't mean to remove the whole thing, I meant that the landmark `nav` could be removed. SR users can navigate by landmark and if you use `nav` in the footer the navigation will be listed as a landmark but you don't need two landmarks if the content is the same.

```html
<div class="l-footer-nav">
  <ul class="l-navigation navigation">
     <li><a href="/">Home</a></li>
      …
  </ul>
</div>
```

**Comment by MadeByMike** [comment]
Oh excellent! I'll do that!
