### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by jshwlkr** [MadeByMike/supermaya#21]
I think that markdown-it is not actually being used, and markdown parsing is probably just being caught by liquid. (I could be wrong.) 

I tried adding markdown-it-footnote to supermaya's markdown filter and I didn't have any success.

```
const markdownIt = require('markdown-it')({
  html: true,
  breaks: true,
  linkify: true
}).use(require('markdown-it-footnote'));

module.exports = function markdown(value) {
  return markdownIt.render(value);
};

```
Changing markdown-it's config in any way doesn't seem to affect the output for me. Is supermaya explicitly expecting something like `{{ content | markdownFilter }}`, or should we be setting the library explicitly via the config api (https://www.11ty.dev/docs/languages/markdown/#optional-set-your-own-library-instance)?

**Comment by MadeByMike** [comment]
I haven't changed any mark-down settings in Supermaya and I don't think I should by default. The intention is to just let 11ty handle the markdown. If people want to configure it through 11ty that's fine.

Is there a bug here or with 11ty?

**Comment by jshwlkr** [comment]
I guess I'm not entirely sure what the purpose of supermaya's explicit markdown filter is then.

**Comment by MadeByMike** [comment]
Oh, my apologies, I was using this to experiment with rendering comments server-side but switched to https://github.com/developit/snarkdown on the client.

You can use this filter if you have data that is not going to be parsed as markdown by 11ty.

**Comment by jshwlkr** [comment]
Ah! I see. Thanks.
