### ISSUE TITLE
Netlify deploy error engine "node" incompatible 

### ISSUE THREAD

**Issue by theapplegates** [MadeByMike/supermaya#25]
The netlify build fails with this error:
error supermaya@1.0.0: The engine "node" is incompatible with this module. Expected version ">=11.0.0". Got "10.20.1"

I'm not a developer so I'm not sure how to fix it.
Thanks 
Paul

**Comment by httpsterio** [comment]
Hey, you can fix this by editing the netlify.toml -file by adding the enviroment by hand, it's the second line here:

```
[build]
  environment = { NODE_VERSION = "12.0.x" }
  command = "npm run build"
  publish = "dist"
[template.environment]
  KEYSTONE_API = "Paste your Keystone API URL here"
```

**Comment by theapplegates** [comment]
Simple enough. Thanks for the help.
