### ISSUE TITLE
Hey amazing developer i have many issues help me if you have time

### ISSUE THREAD

**Issue by rahxuls** [MadeByMike/supermaya#36]
- Why chromium starts downloading when i npm i on the cloned repo. 
  
- I am able to download and push on github and netlify. But I need the comment feature and I don't know how to setup that plz plz plz plz plz help me. Give a small guide plz.  Thanks for making this amazing theme.

**Comment by MadeByMike** [comment]
Really sorry but I need more specific questions to be helpful.
